package com.Feedy.Enum;

public enum OrderStatus {
    ORDER_ACCEPTED,
    FOOD_PREPARING,
    ORDER_PENDING,
    DECLINED,
    ON_THE_WAY,
    DELIVERED,
    COMPLETED,
    CANCEL_BY_RESTAURANT,
    CANCEL_BY_CUSTOMER,
    CANCEL_BY_DELIVERY_AGENT
}
