spring:
  datasource:
    url: jdbc:h2:file:./db/data
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
  mvc:
    log-request-details: true
#    view:
#      prefix: /static
#  basic:
#    enable: false

logging:
  level:
    web: DEBUG
#    org.springframework.web: DEBUG
#    hibernate: ERROR


Server:
  port: 8090